---

- name: Install Java {{ java_version }}
  apt:
    name: "openjdk-{{ java_version }}-jre{{ '-headless' if java_headless }}"
    update_cache: True
    state: present
  register: result
  until: result is success
  retries: 5
  delay: 5

- name: Set as default Java
  alternatives:
    name: java
    path: "/usr/lib/jvm/java-{{ java_version }}-openjdk-amd64/jre/bin/java"

- name: Set JAVA_HOME
  lineinfile:
    dest: /etc/environment
    state: present
    regexp: '^JAVA_HOME'
    line: "JAVA_HOME=/usr/lib/jvm/java-{{ java_version }}-openjdk-amd64"
